import { Oswald, Poppins } from "next/font/google";
import "./globals.css";

const oswald = Oswald({ 
  subsets: ["latin"] ,
  weight:["200","300","400","500","600","700"],
  variable: "--font-oswald",
});
const poppins = Poppins({
   subsets: ["latin"],
   weight:["100","200","300","400","500","600","700","800"],
   variable: "--font-poppins",
  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${oswald.className} ${poppins.className}`}>
        {children}
      </body>
    </html>
  );
}
